### ISSUE TITLE
rockspec error?

### ISSUE THREAD

**Issue by dlbd** [rangercyh/lua-lzw#2]
I get the following error running `luarocks install lzw`:

`
Error: Failed initializing build back-end for build type 'buildin': module 'luarocks.build.buildin' not found:No LuaRocks module found for luarocks.build.buildin
`

There may be a typo in lzw-1.0-0.rockspec. `type = "buildin",` should be `type = "builtin",`. Could you change this and upload an updated version to LuaRocks?

**Comment by siffiejoe** [comment]
While we're at it: "tiny" is probably a bad module name to use on LuaRocks. At least use "lzw.tiny" ...

**Comment by rangercyh** [comment]
all have fix, and new module name is lzw_tiny, thx
